server:
  port: ${PORT:8080}
  shutdown: graceful

spring:
  main:
    lazy-initialization: true
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
  lifecycle:
    timeout-per-shutdown-phase: 20s

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

otp-service:
  key: ${OTP_KEY}
  base-url: ${OTP_BASE_URL}
  customer-id: ${OTP_CUSTOMER_ID}
  email-id: ${OTP_EMAIL_ID}
  token-path: "/auth/v1/authentication/token"
  send-otp-path: "/verification/v3/send"
  validate-path: "/verification/v3/validateOtp"

default:
  phone-number: ${PHONE}
  role: ${Role}